<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class OcsPsaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Lista normalizada de OCS/PSA
        $ocsPsaList = [
            ['nome' => '4-Fisio', 'codigo_interno' => 'OCS-001'],
            ['nome' => 'ABA-Saúde e Qualidade', 'codigo_interno' => 'OCS-002'],
            ['nome' => 'ACR-Cirurgia Geral e Bariátrica', 'codigo_interno' => 'OCS-003'],
            ['nome' => 'Alcance-Clínica de Fisioterapia LTDA', 'codigo_interno' => 'OCS-004'],
            ['nome' => 'AMK-Clínica de Fisioterapia', 'codigo_interno' => 'OCS-005'],
            ['nome' => 'Ana Maria Barros Peres', 'codigo_interno' => 'OCS-006'],
            ['nome' => 'Angela Morais Bueno', 'codigo_interno' => 'OCS-007'],
            ['nome' => 'Angiocore', 'codigo_interno' => 'OCS-008'],
            ['nome' => 'Arcadium', 'codigo_interno' => 'OCS-009'],
            ['nome' => 'Ariel Augusto Britto Rosa', 'codigo_interno' => 'OCS-010'],
            ['nome' => 'Arritmocoor', 'codigo_interno' => 'OCS-011'],
            ['nome' => 'Articular Saúde Integrada', 'codigo_interno' => 'OCS-012'],
            ['nome' => 'Associação Mario Penna', 'codigo_interno' => 'OCS-013'],
            ['nome' => 'Associação Paulo de Tarso', 'codigo_interno' => 'OCS-014'],
            ['nome' => 'Athos Auler', 'codigo_interno' => 'OCS-015'],
            ['nome' => 'Axial', 'codigo_interno' => 'OCS-016'],
            ['nome' => 'Belcoop', 'codigo_interno' => 'OCS-017'],
            ['nome' => 'BFT - Médicos Associados', 'codigo_interno' => 'OCS-018'],
            ['nome' => 'BHCOOP', 'codigo_interno' => 'OCS-019'],
            ['nome' => 'Bianca Dantas Anacleto', 'codigo_interno' => 'OCS-020'],
            ['nome' => 'BIOCOOP', 'codigo_interno' => 'OCS-021'],
            ['nome' => 'Biocor', 'codigo_interno' => 'OCS-022'],
            ['nome' => 'Biogastro', 'codigo_interno' => 'OCS-023'],
            ['nome' => 'Biovisão', 'codigo_interno' => 'OCS-024'],
            ['nome' => 'Bruno Jorge Nakanami', 'codigo_interno' => 'OCS-025'],
            ['nome' => 'Captamed', 'codigo_interno' => 'OCS-026'],
            ['nome' => 'Care-Centro Avançado de Reabilitação', 'codigo_interno' => 'OCS-027'],
            ['nome' => 'Cardoso e Guimarães Fisioterapia', 'codigo_interno' => 'OCS-028'],
            ['nome' => 'Casa de Saúde Imaculada Conceição', 'codigo_interno' => 'OCS-029'],
            ['nome' => 'CBHO', 'codigo_interno' => 'OCS-030'],
            ['nome' => 'Cemelc-Centro Médico Luciano Cardoso', 'codigo_interno' => 'OCS-031'],
            ['nome' => 'Centro de Especialidades Clínicas de Itaúna', 'codigo_interno' => 'OCS-032'],
            ['nome' => 'Centro de Nefrologia de Diálise', 'codigo_interno' => 'OCS-033'],
            ['nome' => 'Centro de Tomografia Computorizada', 'codigo_interno' => 'OCS-034'],
            ['nome' => 'Centro Diagnóstico Ultra Som', 'codigo_interno' => 'OCS-035'],
            ['nome' => 'Centro Mineiro de Medicina Hiperbárica', 'codigo_interno' => 'OCS-036'],
            ['nome' => 'Centro Mineiro Tratamento (Cendor)', 'codigo_interno' => 'OCS-037'],
            ['nome' => 'Centro Oftalmológico MG', 'codigo_interno' => 'OCS-038'],
            ['nome' => 'Centro Saúde Ocular', 'codigo_interno' => 'OCS-039'],
            ['nome' => 'CLINESP-Ruisdael Guimarães', 'codigo_interno' => 'OCS-040'],
            ['nome' => 'Clínica do Saber', 'codigo_interno' => 'OCS-041'],
            ['nome' => 'CLINEMGE', 'codigo_interno' => 'OCS-042'],
            ['nome' => 'Clínica Biophysical de Fisioterapia', 'codigo_interno' => 'OCS-043'],
            ['nome' => 'Clínica de Olhos Dornelas', 'codigo_interno' => 'OCS-044'],
            ['nome' => 'Clínica de Olhos DR Reinaldo', 'codigo_interno' => 'OCS-045'],
            ['nome' => 'Clínica de Olhos Santo Antônio', 'codigo_interno' => 'OCS-046'],
            ['nome' => 'Clínica de Ortopedia e Fisioterapia', 'codigo_interno' => 'OCS-047'],
            ['nome' => 'Clínica Encantar', 'codigo_interno' => 'OCS-048'],
            ['nome' => 'Clínica Excellenz', 'codigo_interno' => 'OCS-049'],
            ['nome' => 'Clínica Existence Serviços', 'codigo_interno' => 'OCS-050'],
            ['nome' => 'Clínica Gontijo Oftalmologia', 'codigo_interno' => 'OCS-051'],
            ['nome' => 'Clínica Lumini', 'codigo_interno' => 'OCS-052'],
            ['nome' => 'Clínica Médica Saúde e Energia', 'codigo_interno' => 'OCS-053'],
            ['nome' => 'Clínica Nefrológica MG', 'codigo_interno' => 'OCS-054'],
            ['nome' => 'Clínica Otoneuro', 'codigo_interno' => 'OCS-055'],
            ['nome' => 'Clínica Reeducar', 'codigo_interno' => 'OCS-056'],
            ['nome' => 'Clínica Tomo Center', 'codigo_interno' => 'OCS-057'],
            ['nome' => 'Clínica Unimagem Diagnósticos', 'codigo_interno' => 'OCS-058'],
            ['nome' => 'Clínica Viva Mais', 'codigo_interno' => 'OCS-059'],
            ['nome' => 'Clinical Center', 'codigo_interno' => 'OCS-060'],
            ['nome' => 'CMH -Medicina Hospitalar', 'codigo_interno' => 'OCS-061'],
            ['nome' => 'Concoop', 'codigo_interno' => 'OCS-062'],
            ['nome' => 'Congregação Irmãs Hospitaleiras', 'codigo_interno' => 'OCS-063'],
            ['nome' => 'Consultório Oftalmológico Nascentes', 'codigo_interno' => 'OCS-064'],
            ['nome' => 'Consultar Consultório Medicina', 'codigo_interno' => 'OCS-065'],
            ['nome' => 'Coopanest', 'codigo_interno' => 'OCS-066'],
            ['nome' => 'COOPCCV MG', 'codigo_interno' => 'OCS-067'],
            ['nome' => 'COOPEDER', 'codigo_interno' => 'OCS-068'],
            ['nome' => 'Coop. dos Servidores do DER', 'codigo_interno' => 'OCS-069'],
            ['nome' => 'Cuidar Bem Fisioterapia', 'codigo_interno' => 'OCS-070'],
            ['nome' => 'DLC-Serviços Médicos', 'codigo_interno' => 'OCS-071'],
            ['nome' => 'Dopsom- Serviço Médico de Propedêutica', 'codigo_interno' => 'OCS-072'],
            ['nome' => 'Eco Vita Diagnóstico', 'codigo_interno' => 'OCS-073'],
            ['nome' => 'Elcenter', 'codigo_interno' => 'OCS-074'],
            ['nome' => 'Eliana Kfuri Pereira', 'codigo_interno' => 'OCS-075'],
            ['nome' => 'Elo-Oftalmologistas Associados', 'codigo_interno' => 'OCS-076'],
            ['nome' => 'Endomedic', 'codigo_interno' => 'OCS-077'],
            ['nome' => 'Equipe Clínica', 'codigo_interno' => 'OCS-078'],
            ['nome' => 'Equipe Vínculo Saúde Infantil', 'codigo_interno' => 'OCS-079'],
            ['nome' => 'Espaço Cardiológico', 'codigo_interno' => 'OCS-080'],
            ['nome' => 'Estação do Saber LTDA', 'codigo_interno' => 'OCS-081'],
            ['nome' => 'Evora Assistência Domiciliar', 'codigo_interno' => 'OCS-082'],
            ['nome' => 'Excellenz- Saúde Integrada', 'codigo_interno' => 'OCS-083'],
            ['nome' => 'Fabrício Melo Bertolini', 'codigo_interno' => 'OCS-084'],
            ['nome' => 'Felice Rosso', 'codigo_interno' => 'OCS-085'],
            ['nome' => 'Felicoop', 'codigo_interno' => 'OCS-086'],
            ['nome' => 'Fisiocenter', 'codigo_interno' => 'OCS-087'],
            ['nome' => 'Fisioport', 'codigo_interno' => 'OCS-088'],
            ['nome' => 'Four Fisioterapia', 'codigo_interno' => 'OCS-089'],
            ['nome' => 'G S H Corp Participações', 'codigo_interno' => 'OCS-090'],
            ['nome' => 'Gastromed', 'codigo_interno' => 'OCS-091'],
            ['nome' => 'GENETICENTER', 'codigo_interno' => 'OCS-092'],
            ['nome' => 'Gianna Aparecida G.Ferreira', 'codigo_interno' => 'OCS-093'],
            ['nome' => 'Ginecoop', 'codigo_interno' => 'OCS-094'],
            ['nome' => 'GOOP (odonto)', 'codigo_interno' => 'OCS-095'],
            ['nome' => 'Guadalupe-Clínica Médica Popular Eireli', 'codigo_interno' => 'OCS-096'],
            ['nome' => 'HCE', 'codigo_interno' => 'OCS-097'],
            ['nome' => 'Hematológica', 'codigo_interno' => 'OCS-098'],
            ['nome' => 'Hemolab', 'codigo_interno' => 'OCS-099'],
            ['nome' => 'Hidekazu Nakanami', 'codigo_interno' => 'OCS-100'],
            // Continuação da lista...
            ['nome' => 'Hospital Belo Horizonte', 'codigo_interno' => 'OCS-101'],
            ['nome' => 'Hospital de Olhos Rui Marinho', 'codigo_interno' => 'OCS-102'],
            ['nome' => 'Hospital Dia Lagoa Santa', 'codigo_interno' => 'OCS-103'],
            ['nome' => 'Hospital e Maternidade Med Center', 'codigo_interno' => 'OCS-104'],
            ['nome' => 'Hospital e Maternidade Santa Mônica', 'codigo_interno' => 'OCS-105'],
            ['nome' => 'Hospital São Lucas', 'codigo_interno' => 'OCS-106'],
            ['nome' => 'Hospital Semper', 'codigo_interno' => 'OCS-107'],
            ['nome' => 'Hospital Socor', 'codigo_interno' => 'OCS-108'],
            ['nome' => 'IMO Inst Mineiro de Obesidade', 'codigo_interno' => 'OCS-109'],
            ['nome' => 'IMOC-Instituto Mineiro de Olhos Contagem', 'codigo_interno' => 'OCS-110'],
            ['nome' => 'IMOL-Instituto Mineiro de Olhos', 'codigo_interno' => 'OCS-111'],
            ['nome' => 'Innovar', 'codigo_interno' => 'OCS-112'],
            ['nome' => 'Inst de Aplicação Bio-Psicológica', 'codigo_interno' => 'OCS-113'],
            ['nome' => 'Inst Radiografia J.Ribamar', 'codigo_interno' => 'OCS-114'],
            ['nome' => 'INTEGRAR', 'codigo_interno' => 'OCS-115'],
            ['nome' => 'Instituto Assistencial Espírita André Luiz', 'codigo_interno' => 'OCS-116'],
            ['nome' => 'Instituto de Atendimento Bio-Psici-Pedagógico', 'codigo_interno' => 'OCS-117'],
            ['nome' => 'Instituto de Hipertensão Arterial', 'codigo_interno' => 'OCS-118'],
            ['nome' => 'Instituto de Medicina Ocular', 'codigo_interno' => 'OCS-119'],
            ['nome' => 'Instituto de Olhos Odair Guimarães', 'codigo_interno' => 'OCS-120'],
            ['nome' => 'Instituto de Olhos Pampulha', 'codigo_interno' => 'OCS-121'],
            ['nome' => 'Instituto de Olhos Santa Luzia', 'codigo_interno' => 'OCS-122'],
            ['nome' => 'Instituto de Otorrino', 'codigo_interno' => 'OCS-123'],
            ['nome' => 'Instituto de Otorrinolaringologia', 'codigo_interno' => 'OCS-124'],
            ['nome' => 'Instituto Hermes Pardini', 'codigo_interno' => 'OCS-125'],
            ['nome' => 'Instituto Saúde da Família', 'codigo_interno' => 'OCS-126'],
            ['nome' => 'IOOG', 'codigo_interno' => 'OCS-127'],
            ['nome' => 'IRA Instituto Roberto Alvarenga', 'codigo_interno' => 'OCS-128'],
            ['nome' => 'Irmandade Nossa Senhora do Patrocínio', 'codigo_interno' => 'OCS-129'],
            ['nome' => 'Itabayana', 'codigo_interno' => 'OCS-130'],
            ['nome' => 'Ivan Dionízio Braga', 'codigo_interno' => 'OCS-131'],
            ['nome' => 'JHF Serviços Médicos', 'codigo_interno' => 'OCS-132'],
            ['nome' => 'Jovânia Maria Alves', 'codigo_interno' => 'OCS-133'],
            ['nome' => 'JQ Fisioterapia e Quiropraxia', 'codigo_interno' => 'OCS-134'],
            ['nome' => 'Kamilla Ragazzi Amaral Duarte', 'codigo_interno' => 'OCS-135'],
            ['nome' => 'Kelly Cristina Nunes B Silva', 'codigo_interno' => 'OCS-136'],
            ['nome' => 'Laboratório Central', 'codigo_interno' => 'OCS-137'],
            ['nome' => 'Laboratório Lapecco', 'codigo_interno' => 'OCS-138'],
            ['nome' => 'Laboratório São Luiz', 'codigo_interno' => 'OCS-139'],
            ['nome' => 'Laboratório Tafuri Patologia', 'codigo_interno' => 'OCS-140'],
            ['nome' => 'Life Center', 'codigo_interno' => 'OCS-141'],
            ['nome' => 'Logus FF&RR Clínica Médica', 'codigo_interno' => 'OCS-142'],
            ['nome' => 'Logus Ultrassonografia', 'codigo_interno' => 'OCS-143'],
            ['nome' => 'LPM Serviços Médicos', 'codigo_interno' => 'OCS-144'],
            ['nome' => 'Madre Tereza', 'codigo_interno' => 'OCS-145'],
            ['nome' => 'Maia Consultoria Medical', 'codigo_interno' => 'OCS-146'],
            ['nome' => 'Maria Aparecida O.Brizola', 'codigo_interno' => 'OCS-147'],
            ['nome' => 'Medical Save', 'codigo_interno' => 'OCS-148'],
            ['nome' => 'Microcirurgia-Ocular Henrique Vizibelli', 'codigo_interno' => 'OCS-149'],
            ['nome' => 'MOVIBE', 'codigo_interno' => 'OCS-150'],
            ['nome' => 'Multi Médicos', 'codigo_interno' => 'OCS-151'],
            ['nome' => 'Mundo Desenvolvimento', 'codigo_interno' => 'OCS-152'],
            ['nome' => 'Natália Chagas Teixeira', 'codigo_interno' => 'OCS-153'],
            ['nome' => 'Nefroclinicas', 'codigo_interno' => 'OCS-154'],
            ['nome' => 'Nefrostar', 'codigo_interno' => 'OCS-155'],
            ['nome' => 'Neo Clinic', 'codigo_interno' => 'OCS-156'],
            ['nome' => 'Neocenter', 'codigo_interno' => 'OCS-157'],
            ['nome' => 'Neoped', 'codigo_interno' => 'OCS-158'],
            ['nome' => 'NUCLEAR MEDCENTER', 'codigo_interno' => 'OCS-159'],
            ['nome' => 'Núcleo de Endoscopia Digestiva', 'codigo_interno' => 'OCS-160'],
            ['nome' => 'Núcleo de Excelência em Oftalmologia', 'codigo_interno' => 'OCS-161'],
            ['nome' => 'Núcleo de Oftalmologia Especializada', 'codigo_interno' => 'OCS-162'],
            ['nome' => 'Núcleo de Otorrino', 'codigo_interno' => 'OCS-163'],
            ['nome' => 'Núcleo de Saúde e Desenvolvimento', 'codigo_interno' => 'OCS-164'],
            ['nome' => 'Núcleo de Saúde Lapecco', 'codigo_interno' => 'OCS-165'],
            ['nome' => 'Nucleoson', 'codigo_interno' => 'OCS-166'],
            ['nome' => 'Oculare', 'codigo_interno' => 'OCS-167'],
            ['nome' => 'OFTALMED', 'codigo_interno' => 'OCS-168'],
            ['nome' => 'Oftalmo-Centro Microcirurgia', 'codigo_interno' => 'OCS-169'],
            ['nome' => 'Oftalmoclinica BH', 'codigo_interno' => 'OCS-170'],
            ['nome' => 'Olavo G F Filho', 'codigo_interno' => 'OCS-171'],
            ['nome' => 'Olhar-Inst-Oftalmologia e Plástica', 'codigo_interno' => 'OCS-172'],
            ['nome' => 'Oncoclinicas', 'codigo_interno' => 'OCS-173'],
            ['nome' => 'Oncomed', 'codigo_interno' => 'OCS-174'],
            ['nome' => 'ONCOOP', 'codigo_interno' => 'OCS-175'],
            ['nome' => 'Oral 3D', 'codigo_interno' => 'OCS-176'],
            ['nome' => 'Orizonti', 'codigo_interno' => 'OCS-177'],
            ['nome' => 'Orto Fisio', 'codigo_interno' => 'OCS-178'],
            ['nome' => 'PHD', 'codigo_interno' => 'OCS-179'],
            ['nome' => 'Plenamente Psicologia P e Saúde', 'codigo_interno' => 'OCS-180'],
            ['nome' => 'Policlínica Salud', 'codigo_interno' => 'OCS-181'],
            ['nome' => 'Postural-Fit Clínica Fisioterapia LTDA', 'codigo_interno' => 'OCS-182'],
            ['nome' => 'Prosperitas Serviços da Saúde', 'codigo_interno' => 'OCS-183'],
            ['nome' => 'Pulsus', 'codigo_interno' => 'OCS-184'],
            ['nome' => 'Radiocare', 'codigo_interno' => 'OCS-185'],
            ['nome' => 'Radioclínica Itaúna LTDA', 'codigo_interno' => 'OCS-186'],
            ['nome' => 'Radiograf', 'codigo_interno' => 'OCS-187'],
            ['nome' => 'Rajacoop', 'codigo_interno' => 'OCS-188'],
            ['nome' => 'Reabilitar e Reeducar', 'codigo_interno' => 'OCS-189'],
            ['nome' => 'Reabilitar Em Casa Excelência', 'codigo_interno' => 'OCS-190'],
            ['nome' => 'Regina de Souza de Santos', 'codigo_interno' => 'OCS-191'],
            ['nome' => 'Ruisdael Guimarães', 'codigo_interno' => 'OCS-192'],
            ['nome' => 'Santa Casa Misericórdia São Vicente de Paula', 'codigo_interno' => 'OCS-193'],
            ['nome' => 'São Marcos Saúde e Med', 'codigo_interno' => 'OCS-194'],
            ['nome' => 'Scan Serviços', 'codigo_interno' => 'OCS-195'],
            ['nome' => 'SCCOOPER', 'codigo_interno' => 'OCS-196'],
            ['nome' => 'Sempcoop', 'codigo_interno' => 'OCS-197'],
            ['nome' => 'Sensorial', 'codigo_interno' => 'OCS-198'],
            ['nome' => 'Sermig', 'codigo_interno' => 'OCS-199'],
            ['nome' => 'Servcor', 'codigo_interno' => 'OCS-200'],
            ['nome' => 'Slice Diagnóstico Volumétrico por Imagem', 'codigo_interno' => 'OCS-201'],
            ['nome' => 'Somap-Viver Bem', 'codigo_interno' => 'OCS-202'],
            ['nome' => 'Spaço Cardiológico', 'codigo_interno' => 'OCS-203'],
            ['nome' => 'Sua-Visão Serviços Médicos', 'codigo_interno' => 'OCS-204'],
            ['nome' => 'TERAPIA INTENSIVA', 'codigo_interno' => 'OCS-205'],
            ['nome' => 'TGD- Saúde LTDA', 'codigo_interno' => 'OCS-206'],
            ['nome' => 'Uromaster', 'codigo_interno' => 'OCS-207'],
            ['nome' => 'Vita Hemoterapia', 'codigo_interno' => 'OCS-208'],
            ['nome' => 'Wani Higino Soares', 'codigo_interno' => 'OCS-209'],
        ];

        $now = Carbon::now();

        foreach ($ocsPsaList as $ocsPsa) {
            DB::table('ocs_psa')->insert([
                'nome' => $ocsPsa['nome'],
                'codigo_interno' => $ocsPsa['codigo_interno'],
                'ativo' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}