services:
  app:
    user: "0:0"
    environment:
      APP_ENV: "homolog"
      APP_DEBUG: "false"
      APP_URL: "http://localhost:8080"
      RUN_MIGRATIONS: "true"
  queue:
    user: "0:0"
    environment:
      APP_ENV: "homolog"
      APP_DEBUG: "false"
  scheduler:
    user: "0:0"
    environment:
      APP_ENV: "homolog"
      APP_DEBUG: "false"
